version: '2'

#Define the services/containers to be run
services:
    web:   #name of the service -> node.js and express web application
      restart: always
      build: .   #specify directory of the Dockerfile
      ports:
       - "3000:3000" #maps the local host port 3000 to container port 3000
      links:
       - database  #link this service to the database service
      volumes:
        - .:/usr/src/app
      depends_on:
       - database
    database:  #name of the service - mongoDB - both the local host and container runs on port 27017
       image: 'mongo:latest' #specify the latest mongoDB image to build container from 